name: nebula
channels:
  - conda-forge
  - defaults
dependencies:
  - json5
  - jupyterlab
  - jupyterlab-lsp
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - notebook
  - seaborn
  - spacy
  - pip:
    - python-lsp-server[all]
    - boto3
    - botocore
    - gitpython==3.1.26
    - ipykernel==6.6.0
    - ipython==7.30.1
    - ipywidgets>=7.5.1
    - jupyterthemes
    - jupyterlab-git
    - nltk
    - numpy
    - pymilvus==1.1.1
    - python-arango==7.2.0
    - opencv-python
    - openai
    - numpy
    - scipy
    - sentence-transformers
    - spacy-wordnet
    - sumproduct
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/NEBULA3PR0JECT/nebula_vg_driver
