name: nebula
channels:
  - conda-forge
  - defaults
dependencies:
  - json5
  - jupyterlab
  - jupyterlab-lsp
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - notebook
  - sentence-transformers
  - pip:
    - python-lsp-server[all]
    - boto3
    - botocore
    - gitpython==3.1.26
    - ipykernel==6.6.0
    - ipython==7.30.1
    - ipywidgets
    - jupyterthemes
    - jupyterlab-git
    - numpy
    - pymilvus==1.1.1
    - python-arango==7.2.0
    - opencv-python
    - numpy
    - scipy
    - git+https://github.com/openai/CLIP.git
